[logging]
# Logging level options: info, debug
log_level = "debug"

# This setting will work for debug mode only (values: filename):
log_file = "cnc.log"
# This setting will work for any but debug level (values: syslog, LogStash):
log_service = "syslog"

[window]
height = 800
width = 600

[server]
bind_intf = "0.0.0.0"
bind_port = 9999
